# Generated by Django 2.0.3 on 2018-03-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualnews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='etiquetas',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
