# Generated by Django 2.0.3 on 2018-04-22 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visualnews', '0005_auto_20180410_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publico',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='puntos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
