# Generated by Django 2.0.3 on 2018-04-28 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visualnews', '0007_auto_20180427_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='publico',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
