# Generated by Django 2.0.3 on 2018-04-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualnews', '0008_auto_20180427_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntuacion',
            name='voto',
            field=models.BooleanField(default=False),
        ),
    ]
