# Generated by Django 2.0.3 on 2018-04-29 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visualnews', '0009_auto_20180428_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntuacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
