# Generated by Django 2.0.3 on 2018-05-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualnews', '0010_auto_20180428_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='img',
            field=models.ImageField(default='media/img/img_default.jpg', upload_to='media/img'),
        ),
    ]
