# Generated by Django 2.0.3 on 2018-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualnews', '0011_noticia_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img',
            field=models.ImageField(default='img/img_default.jpg', upload_to='img'),
        ),
    ]
