# Generated by Django 2.0.3 on 2018-05-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualnews', '0012_auto_20180512_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='img',
        ),
    ]
